token: "your token"
chatId: 228
# for example use '!' to send only global chat, if corresponding plugin installed
msgStartWith: ''
worldNamesDict:
  world: ' â›'
  world_nether: ' ğŸŒ‹'
  world_the_end: ' ğŸ”š'
  deafult: ' '  # if nothing else